[list]
address = chat@geekofarm.com
smtp_batch_size = 5
list_name = Example Mailing List
# Optional SMTP account name used in your .msmtprc file
msmtp_account = chat_test

[imap]
server = imap.dreamhost.com
port = 993
username = chat@geekofarm.com
password = *sekrit*passw0rd*
folder = INBOX
